version: '3'

services:
  db:
    image: postgres
    container_name: postgres_db_container
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - myvpc

  web:
    build: .
    image: django_docker:latest  # For giving custom image name (By default it will take the dictory name on which docker-compose.yml is placed)
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    container_name: docker_practice_proj_container
    volumes:
      - .:/docker_practice_proj
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - myvpc

volumes:
  postgres_data:  # Define the named volume for database data


networks:
  myvpc:
    driver: bridge
